-- Enable RLS
alter default privileges revoke execute on functions from public;

-- 1. Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null default 0,
  disabled boolean default false,
  type text not null, -- 'base_acai' or 'combo_selectable_size'
  description text,
  sizes_key text,
  custom_topping_limits jsonb
);

-- 2. Cup Sizes Table
create table public.cup_sizes (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null default 0
);

-- 3. Neighborhoods Table
create table public.neighborhoods (
  id bigint generated by default as identity primary key,
  name text not null,
  fee numeric not null default 0
);

-- 4. Settings Table (Singleton)
create table public.settings (
  id bigint generated by default as identity primary key,
  store_status text not null default 'auto', -- 'auto', 'open', 'closed'
  delivery_mode text not null default 'both', -- 'both', 'delivery', 'takeout'
  whatsapp_number text,
  address text,
  open_days jsonb default '[]'::jsonb, -- Array of numbers (0-6)
  daily_hours jsonb default '[]'::jsonb, -- Array of objects {open, close}
  weekday_delivery_start_time text,
  weekend_delivery_start_time text
);

-- 5. Orders Table
create table public.orders (
  id text primary key, -- Using string ID from frontend or UUID
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer jsonb not null, -- Stores name, address, etc.
  items jsonb not null, -- Stores the cart items
  subtotal numeric not null default 0,
  discount numeric not null default 0,
  delivery_fee numeric not null default 0,
  total numeric not null default 0,
  status text not null default 'pending' -- 'pending', 'completed', 'cancelled'
);

-- Enable Row Level Security
alter table public.products enable row level security;
alter table public.cup_sizes enable row level security;
alter table public.neighborhoods enable row level security;
alter table public.settings enable row level security;
alter table public.orders enable row level security;

-- Policies (Allowing public access for simplicity as requested, 
-- since the app uses client-side admin auth without Supabase Auth users yet)

-- Products: Read everyone, Write everyone (controlled by app admin)
create policy "Enable read access for all users" on public.products for select using (true);
create policy "Enable insert for all users" on public.products for insert with check (true);
create policy "Enable update for all users" on public.products for update using (true);
create policy "Enable delete for all users" on public.products for delete using (true);

-- Cup Sizes: Read everyone, Write everyone
create policy "Enable read access for all users" on public.cup_sizes for select using (true);
create policy "Enable insert for all users" on public.cup_sizes for insert with check (true);
create policy "Enable update for all users" on public.cup_sizes for update using (true);
create policy "Enable delete for all users" on public.cup_sizes for delete using (true);

-- Neighborhoods: Read everyone, Write everyone
create policy "Enable read access for all users" on public.neighborhoods for select using (true);
create policy "Enable insert for all users" on public.neighborhoods for insert with check (true);
create policy "Enable update for all users" on public.neighborhoods for update using (true);
create policy "Enable delete for all users" on public.neighborhoods for delete using (true);

-- Settings: Read everyone, Write everyone
create policy "Enable read access for all users" on public.settings for select using (true);
create policy "Enable insert for all users" on public.settings for insert with check (true);
create policy "Enable update for all users" on public.settings for update using (true);

-- Orders: Read everyone, Write everyone
create policy "Enable read access for all users" on public.orders for select using (true);
create policy "Enable insert for all users" on public.orders for insert with check (true);
create policy "Enable update for all users" on public.orders for update using (true);

-- Initial Seed Data (Optional - based on common defaults)
insert into public.settings (id, store_status, delivery_mode, whatsapp_number, address)
values (1, 'auto', 'both', '55999999999', 'Rua Exemplo, 123')
on conflict (id) do nothing;
